### PR TITLE
gui(products): creation of product page

### PR DESCRIPTION
**Pull request by AtoLrn**
# Description

Creation of the page and 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested ?

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] New and existing unit tests pass locally with my changes
image

### CODE REVIEW

**Review by gelven4sec — CHANGES_REQUESTED** [review]
Error in console

**Comment by AtoLrn** [comment]
Chut

**Review by gelven4sec — APPROVED** [review]
Finalement je valide

**Comment by AtoLrn** [comment]
[Page de produits](https://trello.com/c/JZJBQtJe/21-page-de-produits)

**Review by lealaroze — APPROVED** [review]
Testé ✔
Remarque : une erreur sur la console

**Pull request merged**
